### ISSUE TITLE
GetIt Package Manager

### ISSUE THREAD

**Issue by AppoPro** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#1]
Can you please add The-Drag-and-Drop-Component-Suite-for-Delphi to GetIt Package Manager ?

**Comment by landrix** [comment]
i have no experiance with that.

**Comment by mkinzler** [comment]
The-Drag-and-Drop-Component-Suite-for-Delphi is available via the Delphinus Package Manager

https://github.com/Memnarch/Delphinus

**Comment by landrix** [comment]
I will try to register the component.

**Comment by AppoPro** [comment]
ok
