### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by srayner** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#10]
Can you provide more detail on how to install this?

After browsing the package folder and opening the package for my version (XE8) in rad studio I can compile or build by right-clicking on the project in the project manager.

But how do I install? There is no install option on the right click menu.
Is there some other trick to installing this?

I probably should know how to do this but I don't. Which is why i'm asking if the instructions could include more detail.

**Comment by landrix** [comment]
Have you choosen the design time package for right click install?

**Comment by srayner** [comment]
Think for reply. Ok, I assume the files prefixed with dcl are the design time packages?
So I now opened the file prefixed with dcl and this give me an install option.

But when I install i get error; Can't load package dclDragDropDXE8.bpl cannot be found.

**Comment by landrix** [comment]
Check your Delphi environment search path, were you can find the generated package BPLs.

**Comment by srayner** [comment]
Is this the Library Path?

The output files seem to go here; C:\Users\Public\Documents\Embarcadero\Studio\16.0\Bpl

I've added this path to the Library path, but still get the same error.

**Comment by landrix** [comment]
Where are the both bpl? In this folder?

**Comment by srayner** [comment]
yep, bpl is in this folder. What do you mean by both? there is only one bpl file?

**Comment by landrix** [comment]
You must compile DragDropDXE8.dpk and dclDragDropDXE8.dpk in that bpl folder

**Comment by srayner** [comment]
Ah, I didn't realize I had to compile two different things.
However, when I compile (or build) DragDropDX8.dpk no output file is generated in the bpl folder.
Maybe it goes somewhere else?

**Comment by landrix** [comment]
Look in the project options of this dpk,where the bpl is.

**Comment by landrix** [comment]
Open allways the .dproj files.not the dpk directly

The bpl should be in ./Library/dxe8/...or something like that

**Comment by srayner** [comment]
ok, yes the output path is ../Library/DXE8/Win32_Release.

So i've found the DragDropDXE8.bpl file.

So I now have two bpl files in two different places.
What do I do with them next?

**Comment by landrix** [comment]
Copy DragDropDXE8.bpl to where dcl...bpl is

**Comment by srayner** [comment]
ok. I've copied DragDropDXE8.bpl to C:\Users\Public\Documents\Embarcadero\Studio\16.0\Bpl
Then i've gone back to the original dclDragDropDXE8.dproj done right-click install and it seems to have worked.

So should the instuctions be;

1. open dclDragDropDXE8.dproj
2. right-click on dclDragDropDXE8.bpl in the project manager, click compile
3. open DragDropDXE8.dproj
4. right-click on DragDropDXE8.bpl in the project manager, click compile
5. copy DragDropDXE8.bpl from ../Library/DXE8/Win32_Release into C:\Users\Public\Documents\Embarcadero\Studio\16.0\Bpl folder
6. Re-open dclDragDropDXE8.dproj
7. right-click on dclDragDropDXE8.bpl in the project manager, click install

or have i made a right pig's ear of the whole thing and there is a much easier way?

**Comment by marlbenn** [comment]
It seems to me that the installation instructions are designed more for people who don't need them, than for those of us who may be very experienced programmers, but are not accustomed to installing run-time packages.  After many hours' struggling, srayner's instructions worked first time for me!

**Comment by mkinzler** [comment]
Alternatively you could use Delphinius for the Download and Install/Update process.

**Comment by landrix** [comment]
i think, every Delphi experienced programmers should know, how Lib-pathes and packages work in Delphi. we have not every Delphi version to test all packages. So everyone should adapt the paths of his component project file to his circumstances.

**Comment by marlbenn** [comment]
Hi Sven

 

I understand what you are saying.  My comment was more an observation and not really a negative criticism.  The whole area of computing, and programming, is so large that no-one can be an expert in all fields.  To you, working in the development of packages, it may be all simple and straightforward, but that is because you have lot of familiarity.  I tend to use packages and addons to Delphi only rarely, because when I have a special requirement I tend to write my own code for it rather than use something written by someone else.

 

I have programmed for very many years, using many different languages and environments, but while I believe Delphi/Pascal is the best around, some parts of the Delphi IDE are not very intuitive.

 

That said, please carry on the good work you are doing.

 

Regards
