### ISSUE TITLE
Always get drCancel dragging from SYSTEM

### ISSUE THREAD

**Issue by AlexanderPD** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#11]
I don't think this is a component's bug, but i still cannot figure how to solve this:

My application runs over the SYSTEM account, and i'm trying to drag from my app and drop on a folder on C:\ (its a folder the SYSTEM account can read and write).

The drag drop works perfectly if i run my app from normal user account or from administrator, but running as SYSTEM always give me drCancel when i drop.

When dragging over the folders the mouse icon always have the correct visual feedback, before the drop i see the "+" near the cursor, but what i get is always a drCancel. 

Do you have any idea on how to solve this? I'm sorry if this problem is not related to the component!

edit:
extra info: on the DropEmptySource feedback i get Effect = 1, as MSDN says (here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms693457(v=vs.85).aspx ) its DROPEFFECT_COPY

edit2:
debugging i found that in DropSource.pas, line 1042, after the DoDragDrop completes, i get this with DRAGDROP_S_DROP result:
LogicalPerformedDropEffect = 0 (DROPEFFECT_NONE)
DropEffect = 0 (DROPEFFECT_NONE)
PerformedDropEffect = -1

forcing Result in drDropCopy doesn't help

**Comment by landrix** [comment]
can you provide an example with source?

**Comment by AlexanderPD** [comment]
you can use any of your demos :)

I just tested with Demos\SourceDemo\SimpleSourceDemo.exe! To reproduce that:

- Download RunAsSys from here: http://blog.delphi-jedi.net/2008/05/08/runassys-10-preview/ (i used the latest version, 1.2)
- Open RunAsSys.exe, a prompt over SYSTEM user will open
- Navigate to your SimpleSourceDemo.exe and open it

done! I'm doing that on Windows 10 x64
Thank you for your answer

**Comment by AlexanderPD** [comment]
well, i still think this is impossibile due a windows limitation.
But at the end of the day, i solved! My app is running on SYSTEM account but silently launches a second .exe that runs over user account. This second exe handles all the drag-drop logic and those two .exe streams the data using named pipe.

Thank you! :)
