### ISSUE TITLE
Set Source files after DropEmptySource.Execute

### ISSUE THREAD

**Issue by AlexanderPD** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#13]
I'm looking at the AsyncFTPClient sample, it's great!

on that sample, when you drag a file from the ftp, you have to wait a little before seeing any visual feedback on the mouse; this because the **AddSourceFile** (line 319) asks the FTP for file properties.

I'd love to have istant-visual feedback on the mouse (so i can also think to let the user drag ftp folders, i have more time to fetch files inside), and i was thinking i can do this:
- When the user drags something i add a single fake dummy file instead real ones
- Do the **DropEmptySource1.Execute** (line 328) so i can let the user drop where he wants
- Adding a FTP fetch procedure at the beginning of **OnGetStream** function (line 379) that removes the dummy file from **TVirtualFileStreamDataFormat(DataFormatAdapterSource.DataFormat)** and adds all the real files from FTP.

i made some tests, but looks like every file i add inside the OnGetStream procedure is totally ignored from _Windows Explorer_, who just want to copy the dummy file.

Is there any way to reach my goal?

**Comment by landrix** [comment]
Sorry, but i have no time at the moment for investigating this issue. I hope you will find some hints.
