### ISSUE TITLE
Delphi 10 Seattle

### ISSUE THREAD

**Issue by cmbant** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#2]
Various stream size (etc.) declarations need to be changed to FixedUInt, LargeUInt, to compile with Delphi 10 Seattle.

**Comment by landrix** [comment]
It compiles for me at DX10. Do you have an example or patch?

**Comment by cmbant** [comment]
Apologies, it looks like I had an old copy in a different directory also in my path, and it wast trying to compile that, not the latest one.
