### ISSUE TITLE
wrong mouse coordinates under W10 in a DPI virtualized application

### ISSUE THREAD

**Issue by tothpaul** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#22]
use the commented code from

https://github.com/JBontes/DragDrop/blob/master/Source/DropTarget.pas#L1259

and add this to fix the point

var
l: TPoint;
m: TMonitor;
mi: TMonitorInfoEx;
dm: DEVMODE;
...
m := Screen.MonitorFromWindow(Result.Handle);
mi.cbSize := SizeOf(mi);
GetMonitorInfo(m.Handle, PMonitorInfo(@mi));
EnumDisplaySettings(mi.szDevice, Cardinal(-1), dm);
l := p;
if dm.dmPelsWidth <> mi.rcMonitor.Width then
begin
l.x := (l.x * mi.rcMonitor.Width) div dm.dmPelsWidth;
end;
if dm.dmPelsHeight <> mi.rcMonitor.Height then
begin
l.y := (l.y * mi.rcMonitor.Height) div dm.dmPelsHeight;
end;

**Comment by LucasBarlow** [comment]
I cannot seem to get this to work. Where do I need to add this code?

**Comment by tothpaul** [comment]
just try TCustomDropTarget.FindTarget on W10 with a non DPI aware application. You'll see that the function return the wrong target because of DPI virtualization.

My code change X/Y according to the DPI difference between the display settings and the virtualized monitor.

**Comment by LucasBarlow** [comment]
The problem I am having is when a monitor is scaled, then only the upper-left portion will accept a drag-drop. The rest of the target just gives me a cross or no-drop cursor. But it only happens on DragEnter. If I enter the target at the right spot then I can drop anywhere on the target. This lead me to think it was a problem with the DragEnter and not the DragOver.

But, I think I figured out what is going on. It may be a bug in Windows 10.
In DragEnter the point variable does not take into account the scale of the monitor, but the DragOver procedure does.

So here is what I did to fix it:
I added this function: (I had to `ShellScaling` to the uses)
```
function ScalePoint(pt: TPoint): TPoint;
var
  m: TMonitor;
  scaleFactor: TDeviceScaleFactor;
begin
  Result := pt;
  m := Screen.MonitorFromPoint(Result);
  if GetScaleFactorForMonitor(m.Handle, scaleFactor) = S_OK then
  begin
    Result.Offset(-m.Left,-m.Top);
    Result.X := trunc(Result.X / (Ord(scaleFactor) / 100));
    Result.Y := trunc(Result.Y / (Ord(scaleFactor) / 100));
    Result.Offset(m.Left,m.Top);
  end;
end;
```

Then in the DragEnter function just before FTarget := FindTarget(pt), I added:
` pt := ScalePoint(pt);`

This seams to have solved the problem for me. I think it solves the FindTarget issue too.

**Comment by rapante85** [comment]
Hy,
i have done the above fix on year ago and it worked very well. 
With windows 10 1803 it seems 2 be broken again... any ideas?

**Comment by LucasBarlow** [comment]
I remember it quit working for me too. I do not remember how I came about it, but here is how I fixed it.
I set the code in the DragEnter function back to the original, removed the ScalePoint function, and made the change in the FindTarget function:

```
  var
    r2: TRect;

    ...

    //Just before the if PtInRect call
    m := Screen.MonitorFromWindow(Result.Handle);
    if GetScaleFactorForMonitor(m.Handle, scaleFactor) = S_OK then
    begin
      r2.Left := round(m.Left - ((m.Left - r.Left) * (Ord(scaleFactor)/100)));
      r2.Top := round(m.Top - ((m.Top - r.Top) * (Ord(scaleFactor)/100)));
      r2.Width := Round(r.Width* (Ord(scaleFactor)/100));
      r2.Height := Round(r.Height* (Ord(scaleFactor)/100));
    end;

    //Then changed the PtInRect call to:
    if PtInRect(r2, p) then
      exit;
```

This has been working for me. I did not test it to see if it still works in the older versions of Windows 10.

**Comment by landrix** [comment]
so, we can close this issue.

**Comment by LucasBarlow** [comment]
I think so. I changed my code back to the original, and it appears rapante85 is right. Thanks for everyone's help.
