### ISSUE TITLE
Unresolved external in C++Builder project under RAD Studio 10.2

### ISSUE THREAD

**Issue by petko** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#26]
I get the following error, when I try using a DragDrop component in a C++Builder project under RAD Studio 10.2:

`[ilink32 Error] Error: Unresolved external '' referenced from C:\USERS\PUBLIC\DOCUMENTS\EMBARCADERO\STUDIO\19.0\DCP\DRAGDROPDR102T.LIB|DragDropPIDL`

The error does not happen in Delphi projects. 

Could you give me any directions how can I fix this?

**Comment by petko** [comment]
Never mind, I've managed to fix it.

**Comment by bdwilton** [comment]
Can you indicate what steps you did for this ?

**Comment by bdwilton** [comment]
Went back to an old laptop as I had forgotten what I had done in the past.

In BPL project the define BCB needs to get added for runtime and designtime.

Additional DropTarget.hpp line needs to get moved from __published to public

__property HWND WinTarget = {read=GetWinTarget, write=SetWinTarget, nodefault};
