### ISSUE TITLE
Compile DragDropD2007 package

### ISSUE THREAD

**Issue by jbrassard1** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#3]
I had to comment this line in DropSource.pas to compile and install DragDropD2007.dpk : 

DragBitmap.AlphaFormat := afDefined; // make sure alpha channel is not pre-multiplied

**Comment by landrix** [comment]
What is the compiler error?

**Comment by jbrassard1** [comment]
[DCC Error] DropSource.pas(723): E2003 Undeclared identifier: 'AlphaFormat'
[DCC Error] DropSource.pas(723): E2003 Undeclared identifier: 'afDefined'
[DCC Error] DropSource.pas(38): F2063 Could not compile used unit 'DropSource'

Thank you!

**Comment by landrix** [comment]
I've changed something. Can you try to compile the source again please?
