### ISSUE TITLE
Delphi 7 incompatibility

### ISSUE THREAD

**Issue by DelphiGit** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#4]
Hi!

Just want to let you know that the declaration of TCustomWideTextClipboardFormat in "DragDropText.pas" has a directive {$IF CompilerVersion >= 15.0} but it needs to be {$IF CompilerVersion >= 17.0} for it to compile in Delphi 7.

Happy New Year and Happy New Code! :)

**Comment by landrix** [comment]
i removed the complete line
