### ISSUE TITLE
Delphi 10 Seattle

### ISSUE THREAD

**Issue by AppoPro** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#5]
Hello 
When i try to build i have this errors:
[dcc32 Fatal Error] DragDropDR10S.dpk(1): E2225 Never-build package 'DragDropDR10S' must be recompiled
[dcc32 Fatal Error] dclDragDropDR10S.dpk(47): E2202 Required package 'DragDropDR10S' not found
Failed
Elapsed time: 00:00:00.2

**Comment by landrix** [comment]
please check the new commit

**Comment by AppoPro** [comment]
Thanks for update.
