### ISSUE TITLE
Can't Install XE7 Package (it builds though)

### ISSUE THREAD

**Issue by CrustyLoaf** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#6]
Hi, for some reason I am able to build both the DragDropDXE7.bpl and dclDragDropDXE7.bpl packages  but when I attempt to 'Install' the latter I get an error saying 'Can't load package, specified module not found' referring to C:\Users\Public\Documents\Embarcadero\Studio\15.0\Bpl\dclDragDropDXE7.bpl (which does exist in that location).

Both of these BPL files compile successfully with no problem, it just fails at the point of installing. I tried going through 'Component->Install Packages' then choosing 'Add' and selecting the 'dclDragDropDXE7.bpl' file but that results in exactly the same error.  I guess there must be some path setting not quite right in the project but I can't see anything obvious.  Any ideas please because I would really love to be able to use this awesome component set in Delphi XE7 like I did in XE2... Thanks.

**Comment by landrix** [comment]
is C:\Users\Public\Documents\Embarcadero\Studio\15.0\Bpl\ Path set in Delphi global environment settings?

**Comment by CrustyLoaf** [comment]
Thanks for the suggestion. I checked and that path is included in the Windows system path variable. I also tried adding '$(BDSCOMMONDIR)\Bpl' to the 'Tools->Options' Library path and Browsing path in Delphi.  Nothing helps unfortunately, I still get the same error dialog (screenshot attached).  Any further ideas?
![dragdropdxe7_error](https://cloud.githubusercontent.com/assets/16792031/12445722/f07c58ae-bf5d-11e5-8457-dac330bce25f.png)

**Comment by landrix** [comment]
btw, the default outputdir for xe7-package is

..\Library\DXE7\$(Platform)_$(Config)

not the Delphi-one

Do you have changed this project-settings?

**Comment by CrustyLoaf** [comment]
Thank you, thank you!

I didn't realise that the compiled 'DragDropDXE7.bpl' actually needed to be in the 'C:\Users\Public\Documents\Embarcadero\Studio\15.0\Bpl\' folder as well as the 'dclDragDropDXE7.bpl' file.  The error message was confusing because it referred to 'dclDragDropDXE7.bpl' but actually it was complaining about the other required 'DragDropDXE7.bpl' which couldn't be located.

Your kind help is much appreciated and I really hope this thread helps someone else as dumb as me!

**Comment by landrix** [comment]
OK ;) i close this issue
