### ISSUE TITLE
Memory Leak when uses list included the EmbeddedWB control

### ISSUE THREAD

**Issue by sjm-github** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#7]
We use Eurekalog and have discovered a memory leak when using the DropComboTarget component and a file is dragged into say a listbox and the uses list of the form includes the EmbeddedWB open source web browser control. When the EmbeddedWB unit is not included no memory leak occurs so I am guessing there is some issue when using them together...maybe something related to OLE and COM?

[eurekalog.txt](https://github.com/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/files/99474/eurekalog.txt)

**Comment by landrix** [comment]
can you attach the project?

**Comment by landrix** [comment]
can you replace this code in DropTarget.pas?

function TCustomDropTarget.SetPerformedDropEffect(Effect: longInt): boolean;
var
  Medium: TStgMedium;
  pde : TPerformedDropEffectClipboardFormat;
begin
  pde := TPerformedDropEffectClipboardFormat.Create;
  try
    pde.Value := Effect;
    Result := pde.SetData(DataObject, pde.FormatEtc, Medium);
  finally
    if Result then
      ReleaseStgMedium(Medium);
    pde.Free;
  end;
end;

**Comment by sjm-github** [comment]
Thanks for that suggestion but it didn't fix the memory leak. I have attached my project but the uses of the project dpr file will reference Eurekalog files and the unit5.pas will include the EmbeddedWb unit so unless you have those you won't be able to run it. It also won't accept my ZIP file for some reason so I have saved off the pas, dfm and dpr as txt files

[Project5dpr.txt](https://github.com/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/files/100590/Project5dpr.txt)
[Unit5dfm.txt](https://github.com/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/files/100587/Unit5dfm.txt)
[Unit5pas.txt](https://github.com/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/files/100591/Unit5pas.txt)

**Comment by landrix** [comment]
where i can get EmbeddedWB.pas?

**Comment by sjm-github** [comment]
You can get EmbeddedWb component from https://github.com/ghquant/Delphi-EmbeddedWB
The memory leak is only very small and always seems to be the same size regardless of how many drag/drop operations is done so to be honest it isn't a big issue.

**Comment by landrix** [comment]
there is a bug in EmbeddedWB

EmbeddedWB.pas calls OleInitialize

this call should changed to
  bOleInitialize := Succeeded(OleInitialize(nil));
because OleInitialize is called twice (DragDrop and EmbeddedWB). And it isn't enough to check the result agains S_OK. it must also checked against S_FALSE

See documentation:
https://msdn.microsoft.com/de-de/library/windows/desktop/ms690134(v=vs.85).aspx

**Comment by sjm-github** [comment]
That's great. Thank you very much.

**Comment by landrix** [comment]
btw EmbeddedWB don't compile in D10 Seattle

**Comment by sjm-github** [comment]
Yes I had to make some changes to the source code of some of the units and create my own packages but I couldn't attach the zip file containing these changes as it keeps saying it isn't a valid file even though it is suppose to accept zip files.

**Comment by landrix** [comment]
ok, good luck :)
