### ISSUE TITLE
Cannot install on Delphi 10 Seattle Update 1

### ISSUE THREAD

**Issue by AlexanderPD** [DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi#9]
Hi, when installing this component from ide on Delphi 10 Seattle update 1 i get this error: 

"Can't load package C:\<my installation path>\Library\DX10S\Win32_Release\dclDragDropDR10S.bpl. The specified module could not be found."

I verified that the file exists. How can i fix it?

**Comment by landrix** [comment]
Please check the closed issues here.

**Comment by AlexanderPD** [comment]
wow, thank you! i read the solution from here: https://github.com/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/issues/6

solved by copying DragDropDR10S.bpl into "C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl\" folder :)

thank you! :+1:

**Comment by landrix** [comment]
;-)
